name: Tests

on: push
permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  #-------------------------
  #       Testing
  #-------------------------
  tests:
    name: Python 3.11
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Unit tests — SINGLE PYTHON VERSION ONLY
        - {name: Python 3.11, python: '3.11', group: test, env: test:all}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - uses: astral-sh/setup-uv@v5
      with:
        version: 0.9.7
        enable-cache: true
        cache-dependency-glob: |
          "pyproject.toml"
          "uv.lock"

    - run: uv venv --python ${{ matrix.python }}

      # Install only what's needed to run tests (no package build/install)
    - name: Install CI dependencies
      run: uv sync --group ${{ matrix.group }}

    - name: Run tests
      run: uv run hatch run +py=${{ matrix.python }} ${{ matrix.env }}

